# Model parameters
model:
  num_classes: 3
  num_points: 16384
  num_neighbors: 16
  channels: [128, 256, 512]

# Training parameters
train:
  batch_size: 4
  learning_rate: 0.001
  weight_decay: 0.0001
  epochs: 100
  lr_decay_step: 20
  lr_decay_rate: 0.5

# Data parameters
data:
  root_dir: "./data/kitti"
  split: "training"
  num_workers: 4
  shuffle: True

# RPN parameters
rpn:
  num_anchors: 2
  pos_iou_thresh: 0.6
  neg_iou_thresh: 0.45
  nms_thresh: 0.8
  nms_pre_size: 1000
  nms_post_size: 100

# Evaluation parameters
eval:
  iou_threshold: 0.5
  nms_threshold: 0.25
  max_objects: 50
